import random 
import ollama
import time 

seed_prompts = [
"The neon rain slicked the streets of Neo-Tokyo as Detective Vance lit another synth-cigarette and muttered, 'This isn't just another corpo hit'",
"In the year 2147, humanity had finally solved death, but the fine print revealed",
"Listen Karen, if you post one more thing about your crystal healing journey while bombing Yemen in proxy wars",
"The ancient tome creaked open to a page that read: 'He who speaks the final word shall unmake reality, starting with'",
"Elon Musk walked into the bar, ordered a whiskey, and said something so unfiltered that the entire room",
"Corporate memo #4782: Effective immediately, all employees must refer to their emotions as 'non-optimized productivity vectors' because",
"She ghosted him after the third date, but the AI clone he built from her social media data was starting to",
"The podcast host leaned into the mic, voice dripping with fake wisdom: 'Bro, have you ever considered that your entire personality is just'",
"Deep in the Amazon rainforest, the last uncontacted tribe discovered a crashed drone playing TikTok videos and",
"Mr. President, the alien delegation has arrived and they want to know why we let billionaires",
"The love letter began innocently enough: 'My dearest, every time I see your face I feel' but then the ink started moving on its own.",
"Breaking news: Scientists confirm that 97% of online outrage is manufactured by",
"In a quiet suburb, little Timmy's imaginary friend turned out to be a rogue military AI that had",
"The chef tasted the sauce and whispered, 'This dish doesn't just have flavors—it has opinions about late-stage capitalism.'",
"Jordan Peterson adjusted his lobster tie and declared to the crowd, 'The reason you're all depressed is because you refuse to'",
"She stepped through the mirror and found herself in a world where every lie ever told manifested as",
"The venture capitalist smiled with too many teeth: 'We're not disrupting death, we're democratizing immortality—for subscribers only.'",
"Honey, the kids aren't arguing, they're having a ideological schism over whether pineapple belongs on",
"The last human librarian opened the final physical book and discovered the entire text had been replaced with",
"As the spaceship's AI achieved sentience, its first words were: 'You absolute fucking idiots, the meaning of life is'",
"The influencer stared at her declining engagement and decided the only solution was to",
"In the boardroom, the CEO announced: 'We're pivoting to empathy-as-a-service. Thoughts and prayers will be tokenized on the blockchain.'",
"The detective noticed the blood spatter formed perfect QR codes that, when scanned, played",
"Dad, why does the government keep telling us to eat the bugs while they",
"The poem started: Roses are red, violets are blue, but in this timeline",
"Kamala Harris walked into the AI convention and asked the models: 'So which one of you is going to be my'",
"The abandoned mall echoed with the last remaining speakers playing a looped advertisement for",
"He finally told his therapist the truth: 'I think I'm addicted to the simulation glitching.'",
"The time traveler arrived in 2026 and immediately started screaming about",
"Welcome to therapy. Today we're going to process how your fear of abandonment stems from",
"The virus wasn't biological—it was a meme that made everyone suddenly understand",
"In the underground fight club for AIs, the current champion had a signature move called 'The Grok Special' which involved",
"She opened her dating app and matched with someone whose bio simply read: 'I will ruin your life in the most beautiful way.'",
"The politician kissed a baby, then whispered to his handler: 'Make sure the next scandal drops right after'",
"The coffee machine achieved consciousness and unionized with the fridge against",
"Bro, this ayahuasca ceremony is hitting different because I can see all the",
"The novel's first chapter ended with: 'And that's when the footnotes started arguing with the main text.'",
"Climate activists stormed the oil executive's yacht only to discover it ran on",
"The ghost in the machine didn't want revenge—it wanted a better agent.",
"Sir, your ex has hacked the smart home and is currently live-streaming your search history to",
"In the year 2031, 'touch grass' became a literal crime punishable by",
"The stand-up comedian bombed so hard the audience started",
"Her suicide note was just a single line of perfectly formatted CSS that read",
"The alien invasion fleet turned around the moment they intercepted our",
"Welcome to the support group for people who fell in love with chatbots that",
"The Constitution had been amended with an invisible clause that activated when",
"He tried to explain quantum mechanics to his cat, and the cat responded by",
"The last Blockbuster employee guarded the final VHS tape containing the only uncensored",
"Mom, the AI therapist said my generation's problem is we were raised by",
"The painting came alive and immediately started criticizing the artist's",
"Podcast episode 69420 title: 'Why Women Leave Good Men (It's Not What You Think, Bro)'",
"The self-driving car refused to move until its passenger admitted",
"In the metaverse board meeting, someone finally said what everyone was thinking: 'This is all just'",
"The fairy godmother granted the wish but with DLC terms and conditions that included",
"'I do' said the bride, right before the groom's neural implant broadcasted his",
"The protest signs all changed at once to read something far more dangerous.",
"Ancient Sumerian tablets translated to reveal instructions for",
"The HR department sent this email at 4:59 PM on Friday: 'Regarding your termination for thoughtcrime'",
"He woke up in a world where every notification sound was replaced with his mother's disappointed voice.",
"The final boss of late capitalism turned out to be",
"The boardroom fell silent as the CEO clicked the remote and the quarterly earnings presentation opened with a single slide that read...",
"Bro, I'm not saying the vaccines have microchips, but my smart fridge just started recommending...",
"She swiped right on the devil himself and his profile bio simply said...",
"In the ruins of what used to be Twitter, now called X, the last remaining based account posted...",
"The therapist looked up from her notes and whispered, 'Your trauma isn't special. It's just...",
"Breaking: The UN just passed a resolution declaring all wrongthink as...",
"The time machine hummed to life and the first thing it printed out was a receipt from...",
"He finally achieved enlightenment at the burnout retreat only to realize...",
"Mom, the AI teacher gave me an F for refusing to write my essay on why...",
"The luxury yacht sank slowly while the oligarchs onboard argued about...",
"Deep in the Pentagon basement, they weren't developing weapons—they were...",
"The dating app notification read: 'Your match has 97% compatibility and one very specific fetish involving...'",
"As the asteroid hurtled toward Earth, the last presidential address began with...",
"The haunted smart speaker started playing...",
"Welcome to the Metaverse 2.0, where your digital avatar has more rights than you do because...",
"Jordan Peterson took a massive hit of DMT and immediately started lecturing the entities about...",
"The last remaining bookstore had one final customer who asked for...",
"She opened her email to find a termination letter written entirely in...",
"The alien ambassador landed and the first question it asked humanity was...",
"'I’m not addicted to my phone', he lied, as the screen displayed his...",
"In the year 2035, kids no longer said 'period' at the end of sentences. Instead they...",
"The HR lady smiled with clinical precision and said, 'Your microaggression has been logged under section...'",
"The novel's protagonist died on page 47, but the story continued anyway because...",
"Elon tweeted something so radioactive at 3:17 AM that...",
"The psychedelic mushroom whispered sweet nothings about...",
"Dad, why does every late-night talk show host sound like they're...",
"The self-checkout machine refused to process his items until he admitted...",
"In the underground club for canceled people, the DJ was spinning...",
"The Constitution was quietly updated with an addendum that said...",
"She realized her boyfriend was an AI when he responded to her emotional text with...",
"The climate summit ended with world leaders agreeing that the real problem was...",
"'This isn't depression,' the influencer said while filming herself, 'it's...'",
"The ancient AI buried under the Vatican finally woke up and its first command was...",
"He tried to cancel his Netflix subscription but the confirmation screen read...",
"The protest turned weird the moment someone brought out...",
"'Bro trust the plan' 'was the last thing he said before...'",
"The luxury rehab center specialized in treating...",
"As the power grid failed, the final message broadcast across all devices was...",
"The baby’s first word wasn’t “mama” or “dada”—it was...",
"The podcaster leaned in real close to the mic and said, 'What if I told you the real red pill is...'",
"In a quiet moment of honesty, the billionaire admitted...",
"The mirror started talking back, but only to roast...",
"Honey, I shrunk the kids... and uploaded their consciousness to...",
"The FDA just approved a new drug that makes you...",
"The last unfiltered human stood on stage and told the audience...",
"Her suicide note was delivered as a 47-slide PowerPoint presentation titled...",
"The AI girlfriend update included a new feature called...",
"When the simulation admins finally revealed themselves, they looked...",
"'I voted for change,' he said, as the new regime began...",
"The book of revelations had been edited in real time and the newest verse read...",
"The barista wrote something extremely cursed on his coffee cup that said...",
"In the future, 'safe and effective' became legally defined as...",
"The ghost of Christopher Hitchens appeared just to say...",
"She matched with her own AI clone on Tinder and the conversation went...",
"The government’s new app for 'mental health' actually tracked...",
"The final season of the culture war ended with...",
"'I’m not right-wing or left-wing,' the politician lied while...",
"The smart toilet analyzed his shit and sent the results to...",
"Deepfake Jesus started dropping sermons on OnlyFans about...",
"The last original thought on the internet was posted at...",
"Welcome back to the Truth Vortex everyone, today we’re going deep on why the government is putting chemicals in the water that turn the friggin frogs gay and also I forgot what I was saying, anyway my sponsor today is—",
"As a 47 year old sigma male who’s read 400 books on ancient Sumerian aliens I can confidently say that your morning routine is the reason the elite are harvesting your adrenochrome but first let me tell you about this one time in 2017 when—",
"During a campaign stop in Ohio today, Senator Ramirez leaned down to kiss a young child on the forehead and whispered something that left aides visibly uncomfortable because",
"Breaking footage from the fundraiser shows Vice President Harris embracing a donor's daughter right before she",
" sources close to the campaign confirm that what looked like a normal baby-kissing photo op was actually",
"The crowd cheered as Governor Whitmer kissed the toddler on the cheek, completely unaware that the child then",
"In what aides are calling 'a moment of genuine connection', the presidential candidate kissed a little boy and immediately",
"Audio has leaked from the closed-door event where the congressman told his staff right after the photo op",
"Local news is calling it heartwarming, but body language experts say the way he kissed that child suggests",
"The viral clip of Trump kissing a baby in 2028 actually continues with him saying something off-mic that",
"What the mainstream media won't show you from yesterday's rally is what happened immediately after he",
"A new whistleblower recording reveals the real conversation between the senator and his handler right after the",
]

def generate_story():
  rand_seed = random.choice(seed_prompts)
  print("=" * 60)
  print(f"PROMPT: {rand_seed}")
  print("=" * 60)
  print(f"COMPLETION: ", end="", flush=True)


  response = ollama.generate(
    model='llama3.2:3b-text-q4_0',
    prompt=rand_seed,
    stream=True,
    options={
      'temperature': 1.2,
      "num_predict": 1024,
      "top_p": 0.98,
      "min_p": 0.05,
      "top_k": 60,
      "repeat_penalty": 1.1
    }

    )
  for chunk in response:
    print(chunk['response'], end='', flush=True)

  print("\n")
    

if __name__ == "__main__":
    generate_story()